### ISSUE TITLE
MongooseError

### ISSUE THREAD

**Issue by suhartoschn** [koolkishan/chat-app-react-nodejs#1]
Help for this error
MongooseError: Operation `users.findOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (C:\CHAT\chat-app\server\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:148:23)

**Comment by MannanFromAptech** [comment]
If you are using MongoDB in local so you can use as mongoose.connect( uri ) mongoose uri not like localhost:27017 You can change this into like this one 127.0.0.1:27017 and your mongoose ll connect with correct local DB Just Try it.

**Comment by MannanFromAptech** [comment]
You have to just change localhost:27017 to 127.0.0.1:27017

**Comment by rudSarkar** [comment]
> Help for this error MongooseError: Operation `users.findOne()` buffering timed out after 10000ms at Timeout. (C:\CHAT\chat-app\server\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:148:23)

If you still facing the issue just change your mongo URL and add `?authSource=admin` end of your database name like below:
```env
MONGO_URL="mongodb://<your-database-url>:27017/<database-name>?authSource=admin"
```

**Comment by HarshTambade** [comment]
can anyone  here how to do the full setup of the zip of this project to get perfect output

**Comment by Mayank-sudo** [comment]
My code worked normaly from one PC but from another one I got the same error. I have MongoDB free hosting by https://www.mongodb.com/ .

I fixed it by adding my current IP to Security - Network Access - IP Access List in the hosting server.

**Comment by rudSarkar** [comment]
> My code worked normaly from one PC but from another one I got the same error. I have MongoDB free hosting by https://www.mongodb.com/ .
> 
> I fixed it by adding my current IP to Security - Network Access - IP Access List in the hosting server.

Can you post the error?

**Comment by Piyushg094** [comment]
can anyone give me a suggestion how the code work i did everything but my database is not working anyone please share me a steps of this how its wort its  please

**Comment by Mayank-sudo** [comment]
am confused your data is not connecting or not establing

**Comment by Piyushg094** [comment]
my data is not establing  user input is not adding in my moogose

**Comment by Piyushg094** [comment]
Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://docs.atlas.mongodb.com/security-whitelist/     this error is genareting

**Comment by hardiii13** [comment]
There may be Problem due to the version of mongoose you have installed. There are some commands that are removed from latest versions.
